### ISSUE TITLE
Unable to install gapps to fresh install of GT-P5113.

### ISSUE THREAD

**Issue by NNickey** [andi34/andi34.github.io#13]
I've been constantly getting crashing and 'Unfortunately' errors after flashing GAPPs including the GAPPS provided from the site  https://andi34.github.io/gapps.html  .

I'm able to run CM13 just fine alone after flashing it, and yes I'm completely wiping all the partitions while I have my micro-sd card detached and only inserted while in the TWRP recovery mode.

TWRP version 2.5.8.0
CM13 - cm-13.0-20160812-UNOFFICIAL-espressowifi.zip
Attempted GAPPS -
     gapps-601-base-20160803-1-signed.zip
     open_gapps-arm-6.0-pico-20160822.zip

**Comment by andi34** [comment]
Update your twrp... Got answered many times on xda
