### ISSUE TITLE
Audio Jack problems

### ISSUE THREAD

**Issue by ghost** [andi34/andi34.github.io#24]
Hi. I have a gt-p5113 running Cyanogenmod 13.0-20161204-NIGHTLY-espressowifi.
I have two problems with the audio jack on my tablet. They are as follows:
1. At random times, particularly after the headphones have been plugged in and not used for several hours, there will be no sound when they are used. I have to unplug them and plug them back in to get them to work.
2. At extremely high volumes that I shouldn't listen to, my right earphone buzzes.

Thank you for creating this amazing ROM.

**Comment by ghost** [comment]
Tell me if you need more information.

**Comment by andi34** [comment]
I am out of development atm and this is not a bug tracker. Use the rom thread and provide proper logs.

**Comment by ghost** [comment]
OK, I'll report it there.
What is this for if it is not a bug tracker?

**Comment by andi34** [comment]
This bugtracker is only meant for andi34.github.io and not for problems with the roms, recoveries etc.
