### ISSUE TITLE
Custom TWRP work?

### ISSUE THREAD

**Issue by smartwalkie** [andi34/andi34.github.io#30]
@andi34 can i pay you to make a TWRP for me for my device? please write me back on skype: wenhan.zhou

**Comment by andi34** [comment]
Nope. But what device you are talking about?

**Comment by smartwalkie** [comment]
a China Device with MTK platform..

**Comment by andi34** [comment]
Maybe you find someone working on MTK devices already. Development "in the blind" (without owning a device) always isn't a good way.

**Comment by smartwalkie** [comment]
@andi34 i can send you the device if you are interested. It is BV6000S from blackview. Every few months, i get new batch and the recovery has to adjust.
